package at.ac.tuwien.dslab2.domain;

public enum EventType {
	AUCTION_STARTED, AUCTION_ENDED, USER_LOGIN, USER_LOGOUT, USER_DISCONNECT, BID_PLACED, BID_OVERBID, BID_WON, USER_SESSIONTIME_MIN, USER_SESSIONTIME_MAX, USER_SESSIONTIME_AVG, BID_PRICE_MAX, BID_COUNT_PER_MINUTE, AUCTION_TIME_AVG, AUCTION_SUCCESS_RATIO
}
